# Generated by Django 3.2.15 on 2024-10-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0005_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bumbu',
            fields=[
                ('bumbu_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'bumbu',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StockBarangBumbu',
            fields=[
                ('stock_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('mamaku_masuk', models.PositiveIntegerField(default=0)),
                ('mamaku_keluar', models.PositiveIntegerField(default=0)),
                ('mamaku_stock', models.PositiveIntegerField(default=0)),
                ('balado_masuk', models.PositiveIntegerField(default=0)),
                ('balado_keluar', models.PositiveIntegerField(default=0)),
                ('balado_stock', models.PositiveIntegerField(default=0)),
                ('aida_masuk', models.PositiveIntegerField(default=0)),
                ('aida_keluar', models.PositiveIntegerField(default=0)),
                ('aida_stock', models.PositiveIntegerField(default=0)),
                ('minyak_masuk', models.PositiveIntegerField(default=0)),
                ('minyak_keluar', models.PositiveIntegerField(default=0)),
                ('minyak_stock', models.PositiveIntegerField(default=0)),
                ('plastik_masuk', models.PositiveIntegerField(default=0)),
                ('plastik_keluar', models.PositiveIntegerField(default=0)),
                ('plastik_stock', models.PositiveIntegerField(default=0)),
                ('kresek_masuk', models.PositiveIntegerField(default=0)),
                ('kresek_keluar', models.PositiveIntegerField(default=0)),
                ('kresek_stock', models.PositiveIntegerField(default=0)),
                ('keterangan', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stock_bumbu',
                'managed': True,
            },
        ),
    ]
