# Generated by Django 3.2.15 on 2024-10-28 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0006_bumbu_stockbarangbumbu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
        migrations.AlterField(
            model_name='stockbarangbumbu',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RekapStockBarang',
            fields=[
                ('rekap_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('pesanan', models.PositiveIntegerField(default=0)),
                ('masuk', models.PositiveIntegerField(default=0)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('barang_keluar', models.PositiveIntegerField(default=0)),
                ('sisa_gudang', models.PositiveIntegerField(default=0)),
                ('terjual', models.PositiveIntegerField(default=0)),
                ('sisa', models.PositiveIntegerField(default=0)),
                ('sisa_akhir', models.PositiveIntegerField(default=0)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('jenis_barang', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dash.product')),
            ],
            options={
                'db_table': 'rekap_stock_barang',
                'managed': True,
            },
        ),
    ]
