# Generated by Django 3.2.15 on 2024-10-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0007_auto_20241028_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rekapstockbarang',
            name='barang_keluar',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rekapstockbarang',
            name='masuk',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rekapstockbarang',
            name='pesanan',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rekapstockbarang',
            name='sisa',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rekapstockbarang',
            name='sisa_akhir',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rekapstockbarang',
            name='sisa_gudang',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rekapstockbarang',
            name='stock',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rekapstockbarang',
            name='terjual',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
