# Generated by Django 3.2.15 on 2024-10-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0008_auto_20241028_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rekapstockbarang',
            name='barang_keluar',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rekapstockbarang',
            name='masuk',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rekapstockbarang',
            name='pesanan',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rekapstockbarang',
            name='sisa',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rekapstockbarang',
            name='sisa_akhir',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rekapstockbarang',
            name='sisa_gudang',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rekapstockbarang',
            name='stock',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rekapstockbarang',
            name='terjual',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stockbarangbumbu',
            name='aida_keluar',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stockbarangbumbu',
            name='aida_masuk',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stockbarangbumbu',
            name='aida_stock',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stockbarangbumbu',
            name='balado_keluar',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stockbarangbumbu',
            name='balado_masuk',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stockbarangbumbu',
            name='balado_stock',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stockbarangbumbu',
            name='kresek_keluar',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stockbarangbumbu',
            name='kresek_masuk',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stockbarangbumbu',
            name='kresek_stock',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stockbarangbumbu',
            name='mamaku_keluar',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stockbarangbumbu',
            name='mamaku_masuk',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stockbarangbumbu',
            name='mamaku_stock',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stockbarangbumbu',
            name='minyak_keluar',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stockbarangbumbu',
            name='minyak_masuk',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stockbarangbumbu',
            name='minyak_stock',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stockbarangbumbu',
            name='plastik_keluar',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stockbarangbumbu',
            name='plastik_masuk',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stockbarangbumbu',
            name='plastik_stock',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='quantity',
            field=models.BigIntegerField(default=0),
        ),
    ]
